config {
    type: "table",
    schema: "raw",
    name: "id_matchmaking_requests_raw_dataform",
    description: "few transformations ",
    tags:["internal_dashboard"]
}

select
id,
CASE when tmap.tutor_name is null then a.tutor_id ELSE tmap.tutor_name end as tutor_id,
  CAST(sub_deal_id AS INT64) AS sub_deal_id,
case 
    when status = 'pending' then 'PENDING'
    when status = 'ignored' then 'IGNORED'
    when status = 'selected' then 'ACCEPTED AND CLAIMED'
    when status = 'rejected' then 'REJECTED'
    when status = 'questioned' then 'QUESITIONED'
    when status = 'missed' and questioned_at is not null then 'IGNORED'
    when status = 'missed' and accepted_at is not null then 'ACCEPTED AND NOT CLAIMED'
    when status = 'missed' and questioned_at is null and accepted_at is null then 'MISSED'
    when status = 'available' and questioned_at is null then 'AVAILABLE'
    when status = 'available' and questioned_at is not null then 'QUESTIONED -> AVAILABLE'
else status end as status,
accepted_at,
questioned_at,
rejected_at,
rejection_reason,
rejection_notes,
created_at,
updated_at,
deleted_at,
  CAST(deal_id AS INT64) AS deal_id,
case subject_id
  WHEN 'c6c7aec6-f27a-11ed-873d-5c60badec1de' THEN 'A Levels'
    WHEN '28991c2b-51fd-426c-9abc-ee7f1d79acc6' THEN 'Accounting'
    WHEN 'fns5454djfbgewhrf43yrtfhehfoyregbg' THEN 'Advanced Viruses'
    WHEN '64af00ce-b3eb-4713-b472-1ed85bfa4916' THEN 'Algebra'
    WHEN 'sdgbhtrfmv5fg6j5gh6k565fasd' THEN 'Algorithm Analysis'
    WHEN '123fdfrgbhtrfmv5fg6j5gh6k565fasd' THEN 'Applied Fluid Mechanics'
    WHEN 'sdgdfbhtrfghmv5fg6j5gh6k565fasd' THEN 'Applied Numerical Methods'
    WHEN '34d386ab-4019-4229-b607-45c11fc80363' THEN 'Arabic'
    WHEN '03f3fca8-0695-49b3-9042-4f4a55b5870c' THEN 'Arabic Handwriting'
    WHEN 'd0dd092a-f279-11ed-873d-5c60badec1de' THEN 'Architecture'
    WHEN 'cb9d4b27-f27a-11ed-873d-5c60badec1de' THEN 'AS Levels'
    WHEN '039cd13b-3d80-46fb-9203-4a1c411c54bf' THEN 'Biology'
    WHEN 'cde1f50d-f27b-11ed-873d-5c60badec1de' THEN 'Business Administration'
    WHEN '23434frgbhtrfmv5fg6j5gh6k565fasd' THEN 'Business Administration(old)'
    WHEN '23b8588a-3567-4517-a8e0-896ef5eb06a0' THEN 'Calculus'
    WHEN 'e62c2384-1a72-42d0-827d-61d7da79322f' THEN 'Chemistry'
    WHEN '2da7eecc-f27a-11ed-873d-5c60badec1de' THEN 'Chinese'
    WHEN 'c76e0518-f279-11ed-873d-5c60badec1de' THEN 'Civil Engineering'
    WHEN '6d0a95e7-8d00-11ee-88c1-0e30bda2af78' THEN 'Communication Skills'
    WHEN 'sdgdfdfrgbhtrfmv5fg6j5gh6k565fasd' THEN 'Computer - Haseb'
    WHEN '975c7eb2-018c-4d00-b3b3-ef4a1c26c592' THEN 'Computer science'
    WHEN 'ea35983a-a8bf-4f3d-b706-148eb5887592' THEN 'Computer science'
    WHEN '19233a4d-f975-48de-86ed-c3ed7dbffa1a' THEN 'Critical Thinking'
    WHEN 'ghjbfjkbsdkfjrdf68372rtgfb3y4efg' THEN 'Cyber security'
    WHEN '15c61ad2-8bc3-4eeb-9c05-99e542a62205' THEN 'Daily Agenda Support'
    WHEN '13521a7b-0849-4759-a29b-b9e204cc34e6' THEN 'Daily Agenda Support'
    WHEN 'b837bfd5-302f-4b60-a9a2-5d56f62b34d3' THEN 'Data Science'
    WHEN '5b2efdaa-f27a-11ed-873d-5c60badec1de' THEN 'Dentistry'
    WHEN 'rutyiouriyhfitghnbfhjuvghbergdfnbg' THEN 'Differential Equations'
    WHEN 'dfbhtrfmv5fg6j5gh6k565fasd' THEN 'Digital Analysis'
    WHEN 'cf41cbd1-3523-46a3-b8e9-c32e223d7897' THEN 'Economics'
    WHEN 'be48a5fb-f279-11ed-873d-5c60badec1de' THEN 'Electrical Engineering'
    WHEN 'e8036965-3be1-402c-a88f-9c6a547fbab1' THEN 'Elementary Math'
    WHEN '3b3d8255-6b63-40fc-b77e-4b6ab55bdea5' THEN 'Elementary Science'
    WHEN 'sdgdfbhtrfmv5fg6j5gh6k565fasd' THEN 'Engineering Mechanics'
    WHEN 'a8c48bf7-f3a1-4481-85c0-441880b9e55f' THEN 'English'
    WHEN 'sdgdfbhtrfg6k565fasd' THEN 'Excel'
    WHEN 'd803540b-f27b-11ed-873d-5c60badec1de' THEN 'Finance'
    WHEN 'sadfhshjdf843ryfgdsough' THEN 'Finance(old)'
    WHEN '18caf3aa-26d7-4ad7-952d-3ddd4404dde8' THEN 'Foundational Arabic'
    WHEN '73335fb4-a548-4e19-8325-1ea018de78be' THEN 'Foundational English'
    WHEN '6dae8582-e66b-4c83-95fb-456abe79abbc' THEN 'French'
    WHEN 'b86dcde6-f27a-11ed-873d-5c60badec1de' THEN 'GAT (General)'
    WHEN 'abd2c89f-f27a-11ed-873d-5c60badec1de' THEN 'GAT (Quantitative)'
    WHEN 'b006dfbf-f27a-11ed-873d-5c60badec1de' THEN 'GAT (Verbal)'
    WHEN '6be48abb-aa15-11ee-88c1-0e30bda2af78' THEN 'GCSE'
    WHEN 'a68095af-22eb-4a59-b066-c0805c0847b1' THEN 'General Arabic'
    WHEN '46b6b721-2e73-4702-b47e-e73b2b42e4ee' THEN 'General English'
    WHEN '3651964b-8445-4342-9e4c-409deb898f23' THEN 'General Exams Revision'
    WHEN '200a7e62-3910-3368-9387-26c544821f56' THEN 'General Math'
    WHEN '200a7e62-3910-3368-9387-26c544821f66' THEN 'General Science'
    WHEN 'ff987831-cf10-42da-92fc-3ecbc2beb43f' THEN 'Geometry'
    WHEN '302172a5-8029-4a14-be6d-03da470bd4c7' THEN 'German'
    WHEN '200a7e62-3910-3368-9387-26c544821f76' THEN 'GMAT'
    WHEN '200a7e62-3910-3368-9387-26c544821f86' THEN 'GRE'
    WHEN 'ee7d694f-50b6-4fa0-a666-4fc6319849d2' THEN 'Guitar'
    WHEN 'fnsdjfbgewhrf43yrtfhehfoyregbg' THEN 'High School Math'
    WHEN '537a9fde-bf55-4dc4-bac6-11623136f5a6' THEN 'IELTS'
    WHEN '0526c797-b05f-4fc3-9270-51334c63ec9f' THEN 'Islamic Studies'
    WHEN 'f40f7038-db28-48b9-9c03-2215986f3e42' THEN 'Law'
    WHEN '26b8bf98-8d01-11ee-88c1-0e30bda2af78' THEN 'Loghati'
    WHEN '1c175359-b262-4906-a57b-f229c799630a' THEN 'Maths'
    WHEN 'sdgdfbhtrfmv5fdfgg6j5gh6k565fasd' THEN 'Mawhiba Exam'
    WHEN '7bdea6ee-1e06-4c68-8493-71c823e092b4' THEN 'Middle School Math'
    WHEN '3fe32b51-7d88-40ca-a845-67bb67cedea4' THEN 'Middle School Science'
    WHEN '54dd3376-81a2-426a-8e87-735613d5b378' THEN 'Middle School Physics'
    WHEN '52362001-f27a-11ed-873d-5c60badec1de' THEN 'Pharmacy'
    WHEN '07f5507f-f2fe-11ed-873d-5c60badec1de' THEN 'Programming'
    WHEN 'b40926f4-823e-4057-9754-f531c974cc0d' THEN 'Qudrat (aracbic)'
    WHEN '0603857c-cae9-4ce8-bff2-4f64822bc4e3' THEN 'Qudrat (General)'
    WHEN '68542f18-fcdf-41c5-8f66-7cc2ddb4ffa9' THEN 'Qudrat (Quantitative)'
    WHEN 'dd24f12d-931a-45ef-a1d2-cf3ead74432f' THEN 'Qudrat (verbal)'
    WHEN 'bc8cacfa-f27a-11ed-873d-5c60badec1de' THEN 'SAAT'
    WHEN '5c601e68-94cf-4f68-84b4-09ba05cac894' THEN 'SAAT'
    WHEN '50be280e-cc7b-4ae7-a4f1-db855a641dce' THEN 'Social Studies'
    WHEN '3b7c6696-b1d3-4f69-a6a9-5e5d5bee4b6d' THEN 'Statistics'
    WHEN '98471931-522e-11ee-88c1-0e30bda2af78' THEN 'STEP Exam'
    WHEN '7e1eb8ca-eb54-4bac-862b-dda6ff95a9ce' THEN 'Tahsili (Arabic)'
    WHEN '14a8bfe3-7950-4e62-a876-73773cf670bd' THEN 'Tahsili'
    WHEN '76960f25-3145-11ee-b9c5-0e30bda2af78' THEN 'Thesis'
    WHEN 'sdgdfbhtrfghmv5gh6k565fasd' THEN 'University Math'
    WHEN 'gewhrf43yrtfhehfoyregbg' THEN 'Thinking Skills'
    WHEN 'sdgdfbhtrfghmv5fg6j5565fas44' THEN 'Pikado English'
    WHEN 'c936a768-9b11-4cf5-865e-e1ae3d4b43f9' THEN 'High School Math'
    WHEN '6fbe3f3b-f640-4094-984c-ff9de3c87667' THEN 'GMAT'
    WHEN '684e7401-72c0-409f-9c2c-914aebd1e598' THEN 'GAT (Quantitative)'
    WHEN 'e6604aed-9fe9-460d-823b-a6490d0c5768' THEN 'IELTS (General)'
    WHEN 'fc99d784-ed3d-4f40-83a9-ae77fb7b24a6' THEN 'Elementary Islamic Studies'
    WHEN '995999ae-8d7e-4807-a8a8-79ed73fe73e5' THEN 'High School Physics'
    WHEN '5b934092-a8ed-4bd3-a64c-a0478221356e' THEN 'Other Subject'
    WHEN '62915e5a-2d7e-4bf3-8281-407b2709002a' THEN 'Excel'
    WHEN '6475f6cd-951f-43c7-ab5b-b66392b022f8' THEN 'Elementary Science'
    WHEN '78d8d852-5e52-446a-8ba3-e14142446845' THEN 'High School Biology'
    WHEN '7c616c04-c7a7-413a-8bb4-1d79ed2ca94d' THEN 'High School Chemistry'
    WHEN '14bc636c-dcad-4971-b4f9-10e962eaa963' THEN 'Cyber security'
    WHEN '9f620998-76cd-4fe2-9fcd-0895c83de135' THEN 'University Statistics'
    WHEN 'b3ae0d80-2f94-427b-ac5b-cb9ea1a1dd8f' THEN 'SAT'
    When 'd2cafe37-14c6-4fd4-87c3-e2802be04597' Then 'High School Economics'
    When '007a2286-e9b5-4494-ac53-bea7fca50085' Then 'Beginner Chinese'
else subject_id end as subject_id,
notification_id,
is_pledged
from
`al-gooru.staging.id_matchmaking_requests`  a 
left join `al-gooru.production.tutor_id_mapping_final` tmap on a.tutor_id = tmap.tutor_id 