config {
    type: "table",
    schema: "production",
    name: "id_subjects_prod_dataform",
    description: "few transformations ",
    tags:["internal_dashboard"]
}

select
id,
categoryId,
nameAr,
nameEn,
isStudentsLookFor,
isDeleted,
isTest,
order_test,
isForStudent,
addedBy,
created_at,
updated_at,
hasLevel,
defaultLevel,
chatbot_mb,
is_active
from
${ref('id_subjects_raw_dataform')}