config {
    type: "table",
    schema: "raw",
    name: "id_subjects_raw_dataform",
    description: "few transformations ",
    tags: ["internal_dashboard"]
}

SELECT
  id,
  categoryId,
  nameAr,
  nameEn,
  isStudentsLookFor,
  isDeleted,
  isTest,
  order_test,
  isForStudent,
  addedBy,
  created_at,
  updated_at,
  hasLevel,
  defaultLevel,
  chatbot_mb,
  is_active
FROM
  al-gooru.hubspot.id_subjects
