config {
    type : 'incremental',
    name : 'dim_course',
    schema : 'marjala',
    protected : false ,
    uniqueKey : ['course_id'],
    tags: ["marjala"]
}
SELECT
  c.id          AS course_id,
  c.code        AS course_code,
  c.name_en,
  c.name_ar,
  c.price       AS base_price,
  round(safe_divide(price,3.65),0)       AS base_price_in_USD,
  c.price_type,
  c.created_at,
  c.updated_at,
  c.deleted_at
FROM al-gooru.hubspot.id_courses c
WHERE c.deleted_at IS NULL
